with a as (SELECT LEVEL-1 a FROM DUAL
CONNECT BY LEVEL < 42),
b as (
SELECT LEVEL-1 b FROM DUAL
CONNECT BY LEVEL < 42
),
c as (select a.a UKUPNI_STAZ, b.b STAZ_TS from a left outer join b on a.a>=b.b),
d as (
SELECT
UKUPNI_STAZ,
STAZ_TS,
COUNT(BROJ_RADNIKA) BROJ
FROM 
(SELECT
XXHOS.pen_3112_g UKUPNI_STAZ, 
XXHOS.staz_ts_g STAZ_TS,
XXHOS.person_id BROJ_RADNIKA,
PAPF.SEX POL
from 
XXMT_HR_OBRACUN_RS_V XXHOS LEFT  OUTER JOIN PER_ALL_PEOPLE_F PAPF ON XXHOS.PERSON_ID=PAPF.PERSON_ID
WHERE 
1=1
AND :P_DATUM BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE)
WHERE 
1=1
and POL='M'
GROUP BY UKUPNI_STAZ, STAZ_TS
order by LENGTH(UKUPNI_STAZ),UKUPNI_STAZ,STAZ_TS
)
select 
C.UKUPNI_STAZ UKUPNI_STAZ, 
C.STAZ_TS STAZ_TS, 
nvl(D.BROJ,0) BROJ_RADNIKA 
from C 
LEFT OUTER JOIN D on (c.UKUPNI_STAZ=d.UKUPNI_STAZ and c.staz_TS=d.staz_TS)
order by 1,2
;
