SELECT
ROWNUM
,RB_MT
,BROJ_RADNIKA
,PREZIME_IME
,DATUM_OD
,DATUM_DO
,MT_SIFRA
,MT_NAZIV
,GRUPA_ZA_PLAN
FROM (
SELECT
 ROW_NUMBER() OVER (PARTITION BY GZPB order by PREZIME_IME) RB_MT
,BROJ_RADNIKA
,PREZIME_IME
,DATUM_OD
,DATUM_DO
,MT_SIFRA
,MT_NAZIV
,GRUPA_ZA_PLAN
FROM (
SELECT
--ROW_NUMBER() OVER (PARTITION BY FFVV.DESCRIPTION order by FFVV.FLEX_VALUE_MEANING, PAPF.LAST_NAME||' '||PAPF.FIRST_NAME) RB_MT
PAPF.EMPLOYEE_NUMBER BROJ_RADNIKA
,PAPF.LAST_NAME||' '||PAPF.FIRST_NAME PREZIME_IME
,PAAF.EFFECTIVE_START_DATE DATUM_OD
,PAAF.EFFECTIVE_END_DATE DATUM_DO
,PCAK.SEGMENT1 MT_SIFRA
,FFVV2.DESCRIPTION MT_NAZIV
,FFVV.DESCRIPTION GRUPA_ZA_PLAN
,FFVV.FLEX_VALUE_MEANING GZPB
FROM 
PER_ALL_PEOPLE_F PAPF
LEFT OUTER JOIN PER_ALL_ASSIGNMENTS_F PAAF ON PAPF.PERSON_ID=PAAF.PERSON_ID
LEFT OUTER JOIN PAY_COST_ALLOCATIONS_F PCAF ON PAAF.ASSIGNMENT_ID=PCAF.ASSIGNMENT_ID
LEFT OUTER JOIN PAY_COST_ALLOCATION_KEYFLE_KFV PCAK ON PCAF.COST_ALLOCATION_KEYFLEX_ID=PCAK.COST_ALLOCATION_KEYFLEX_ID
LEFT OUTER JOIN PER_PERSON_TYPES_TL PPT ON PAPF.PERSON_TYPE_ID=PPT.PERSON_TYPE_ID
LEFT OUTER JOIN fnd_flex_values_vl FFVV ON PAAF.ASS_ATTRIBUTE11=FFVV.FLEX_VALUE
LEFT OUTER JOIN fnd_flex_values_vl FFVV2 ON PCAK.SEGMENT1=FFVV2.FLEX_VALUE
WHERE 
1=1
AND :P_DATUM BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
AND :P_DATUM BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
AND :P_DATUM BETWEEN PCAF.EFFECTIVE_START_DATE AND PCAF.EFFECTIVE_END_DATE
AND PPT.USER_PERSON_TYPE='Radnik'
AND PCAF.COST_ALLOCATION_KEYFLEX_ID is not null
AND PPT.LANGUAGE='LSR'
AND (EMPLOYEE_CATEGORY IS NOT NULL OR EMPLOYMENT_CATEGORY IS NOT NULL)
AND ffvv.FLEX_VALUE_SET_ID=(select FLEX_VALUE_SET_ID from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME like 'XXTS_GRUPA_ZA_PLAN')
AND ffvv2.FLEX_VALUE_SET_ID=(select FLEX_VALUE_SET_ID from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME like 'XXTS_MESTA_TROŠKA')
)
ORDER BY GZPB
)
;



SELECT 
DESCRIPTION,
FLEX_VALUE_MEANING
FROM APPLSYS.FND_FLEX_VALUES_TL 
WHERE FLEX_VALUE_ID 
IN (SELECT FLEX_VALUE_ID FROM FND_FLEX_VALUES WHERE FLEX_VALUE_SET_ID=(select FLEX_VALUE_SET_ID from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME like 'XXTS_MESTA_TROŠKA')) 
AND LANGUAGE='LSR';

SELECT * FROM fnd_flex_values_vl;
SELECT * FROM PAY_COST_ALLOCATIONS_F;
SELECT * FROM PAY_COST_ALLOCATION_KEYFLE_KFV;