SELECT
T1.POSITION_ID
,T1.SPREMA
,T1.MAX_SPREMA
FROM
(
SELECT 
POSITION_ID POSITION_ID
,POEI_INFORMATION1 SPREMA
,MAX(POEI_INFORMATION1) OVER (PARTITION BY POSITION_ID) MAX_SPREMA
FROM 
HR.PER_POSITION_EXTRA_INFO 
WHERE
1=1
AND INFORMATION_TYPE='XXTS_OBRAZOVANJE_ISKUSTVO'
)T1
WHERE T1.SPREMA<>T1.MAX_SPREMA
;

SELECT * FROM PER_POSITIONS;

SELECT * FROM HR.HR_ALL_POSITIONS_F WHERE POSITION_ID=75645;
SELECT * FROM PER_POSITION_EXTRA_INFO WHERE POSITION_ID=75645;

SELECT * FROM HR.PER_QUALIFICATION_TYPES;


SELECT * FROM FND_FLEX_VALUE_SETS WHERE FLEX_VALUE_SET_NAME = 'XXTS_STRUCNA_SPREMA';

SELECT FLEX_VALUE_ID FROM FND_FLEX_VALUES WHERE FLEX_VALUE_SET_ID=1015814;

SELECT 
FLEX_VALUE_MEANING,
DESCRIPTION
FROM 
FND_FLEX_VALUES_TL 
WHERE 
FLEX_VALUE_ID 
IN 
(SELECT 
FLEX_VALUE_ID 
FROM FND_FLEX_VALUES 
WHERE FLEX_VALUE_SET_ID=(SELECT FLEX_VALUE_SET_ID FROM FND_FLEX_VALUE_SETS WHERE FLEX_VALUE_SET_NAME = 'XXTS_STRUCNA_SPREMA')
AND LANGUAGE='LSR'
);


SELECT DISTINCT POSITION_ID, POEI_INFORMATION1, COUNT(*) FROM HR.PER_POSITION_EXTRA_INFO 
WHERE INFORMATION_TYPE='XXTS_OBRAZOVANJE_ISKUSTVO' 
HAVING COUNT(*)>1
GROUP BY POSITION_ID, POEI_INFORMATION1;