select
T1.STATUS STATUS,
count(*) BROJ
from
(SELECT
PAPF.EMPLOYEE_NUMBER EMPLOYEE_NUMBER,
CASE
WHEN PAAF.EMPLOYMENT_CATEGORY IN (SELECT LOOKUP_CODE FROM FND_LOOKUP_VALUES WHERE LOOKUP_TYPE LIKE 'EMP_CAT' AND LANGUAGE='LSR' AND MEANING='Odredjeno') THEN 'ODRE?ENO'
WHEN PAAF.EMPLOYMENT_CATEGORY IN (SELECT LOOKUP_CODE FROM FND_LOOKUP_VALUES WHERE LOOKUP_TYPE LIKE 'EMP_CAT' AND LANGUAGE='LSR' AND MEANING='Neodredjeno') THEN 'NEODRE?ENO'
END STATUS
FROM
PER_ALL_PEOPLE_F PAPF
LEFT OUTER JOIN PER_ALL_ASSIGNMENTS_F PAAF ON PAPF.PERSON_ID=PAAF.PERSON_ID
LEFT OUTER JOIN PER_PERSON_TYPES_TL PPTL ON PAPF.PERSON_TYPE_ID=PPTL.PERSON_TYPE_ID
WHERE
1=1
AND PAAF.ASSIGNMENT_STATUS_TYPE_ID=1
AND (PAAF.EMPLOYEE_CATEGORY IS NOT NULL OR PAAF.EMPLOYMENT_CATEGORY IS NOT NULL)
AND :P_DATUM BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
AND :P_DATUM BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
AND PPTL.LANGUAGE = 'LSR'
AND UPPER(PPTL.USER_PERSON_TYPE)=UPPER('Radnik')) T1
group by T1.STATUS
ORDER BY count(*) DESC;



select
count(*)
from
(SELECT
PAPF.EMPLOYEE_NUMBER EMPLOYEE_NUMBER,
CASE
WHEN PAAF.EMPLOYMENT_CATEGORY IN (SELECT LOOKUP_CODE FROM FND_LOOKUP_VALUES WHERE LOOKUP_TYPE LIKE 'EMP_CAT' AND LANGUAGE='LSR' AND MEANING='Odredjeno') THEN 'ODRE?ENO'
WHEN PAAF.EMPLOYMENT_CATEGORY IN (SELECT LOOKUP_CODE FROM FND_LOOKUP_VALUES WHERE LOOKUP_TYPE LIKE 'EMP_CAT' AND LANGUAGE='LSR' AND MEANING='Neodredjeno') THEN 'NEODRE?ENO'
END STATUS
FROM
PER_ALL_PEOPLE_F PAPF
LEFT OUTER JOIN PER_ALL_ASSIGNMENTS_F PAAF ON PAPF.PERSON_ID=PAAF.PERSON_ID
LEFT OUTER JOIN PER_PERSON_TYPES_TL PPTL ON PAPF.PERSON_TYPE_ID=PPTL.PERSON_TYPE_ID
WHERE
1=1
AND PAAF.ASSIGNMENT_STATUS_TYPE_ID=1
AND (PAAF.EMPLOYEE_CATEGORY IS NOT NULL OR PAAF.EMPLOYMENT_CATEGORY IS NOT NULL)
AND (:P_DATUM < PAPF.EFFECTIVE_END_DATE AND :P_DATUM2 > PAPF.EFFECTIVE_START_DATE)
AND (:P_DATUM < PAAF.EFFECTIVE_END_DATE AND :P_DATUM2 > PAAF.EFFECTIVE_START_DATE)
AND PPTL.LANGUAGE = 'LSR'
AND UPPER(PPTL.USER_PERSON_TYPE)=UPPER('Radnik')) T1
group by T1.STATUS;






SELECT * FROM FND_LOOKUP_TYPES WHERE LOOKUP_TYPE LIKE 'EMP_CAT';

SELECT LOOKUP_CODE FROM FND_LOOKUP_VALUES WHERE LOOKUP_TYPE LIKE 'EMP_CAT' AND LANGUAGE='LSR' AND MENANING='Odredjeno';

