WITH A AS
(
SELECT 
PAPF.EMPLOYEE_NUMBER BROJ_RADNIKA
,NVL(SUBSTR(PAAF.ASS_ATTRIBUTE5,1,(INSTR(PAAF.ASS_ATTRIBUTE5,' ',1))-1),'NDP-X') PRIZNATA_SS
FROM 
PER_ALL_PEOPLE_F PAPF
LEFT OUTER JOIN PER_ALL_ASSIGNMENTS_F PAAF ON PAPF.PERSON_ID=PAAF.PERSON_ID
LEFT OUTER JOIN PER_PERSON_TYPES_TL PPT ON PAPF.PERSON_TYPE_ID=PPT.PERSON_TYPE_ID
WHERE 
1=1
AND :P_DATUM BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
AND :P_DATUM BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
AND PPT.USER_PERSON_TYPE='Radnik'
AND PPT.LANGUAGE='LSR'),
B AS 
(
SELECT 
DISTINCT PQV.NAME SS
,PQT.RANK RANG_SS
FROM
PER_QUALIFICATIONS_V PQV
LEFT OUTER JOIN PER_QUALIFICATION_TYPES PQT ON PQV.QUALIFICATION_TYPE_ID=PQT.QUALIFICATION_TYPE_ID
),
C AS
(SELECT
COUNT(A.BROJ_RADNIKA) BR_RADNIKA
,A.PRIZNATA_SS STRUCNA_S
FROM A LEFT OUTER JOIN B ON A.PRIZNATA_SS=B.SS
GROUP BY A.PRIZNATA_SS,B.RANG_SS 
ORDER BY B.RANG_SS DESC)
SELECT
ROWNUM RB
,BR_RADNIKA
,STRUCNA_S
FROM C;



--ORDER BY B.RANG_SS DESC;