WITH A AS
(
SELECT 
PAPF.PERSON_ID
,PAPF.EMPLOYEE_NUMBER BROJ_RADNIKA
,NVL(SUBSTR(PAAF.ASS_ATTRIBUTE5,1,(INSTR(PAAF.ASS_ATTRIBUTE5,' ',1))-1),'NDP-X') PRIZNATA_SS
FROM 
PER_ALL_PEOPLE_F PAPF
LEFT OUTER JOIN PER_ALL_ASSIGNMENTS_F PAAF ON PAPF.PERSON_ID=PAAF.PERSON_ID
LEFT OUTER JOIN PER_PERSON_TYPES_TL PPT ON PAPF.PERSON_TYPE_ID=PPT.PERSON_TYPE_ID
where
1=1
AND :P_DATUM BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
AND :P_DATUM BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
AND PPT.USER_PERSON_TYPE='Radnik'
AND PPT.LANGUAGE='LSR'
AND PAAF.ASS_ATTRIBUTE5 IS NOT NULL),
B as
(
select 
PERSON_ID,
STVARNA_SS,
RANG
from 
(
select 
pq.person_id PERSON_ID
,pqt.name STVARNA_SS
,pqt.rank RANG
from 
PER_QUALIFICATIONS pq 
left outer join 
PER_QUALIFICATION_types pqt on PQ.QUALIFICATION_TYPE_ID=PQT.QUALIFICATION_TYPE_ID
) Q1)
SELECT 
A.PERSON_ID
,A.BROJ_RADNIKA
,A.PRIZNATA_SS
,B.STVARNA_SS
FROM A LEFT OUTER JOIN B ON A.PERSON_ID=B.PERSON_ID
ORDER BY PERSON_ID;