SELECT 
T2.BR_GRUPE_STAROST
,T2.GRUPA_STAROST
,COUNT(*) BROJ_ZAPOSLENIH
FROM
(select
CASE 
WHEN T1.STAROST <= 30 THEN 1
WHEN T1.STAROST > 30 AND T1.STAROST<=40 THEN 2
WHEN T1.STAROST > 40 AND T1.STAROST<=50 THEN 3
WHEN T1.STAROST > 50 THEN 4 
END BR_GRUPE_STAROST
,CASE 
WHEN T1.STAROST <= 30 THEN '<=30'
WHEN T1.STAROST > 30 AND T1.STAROST<=40 THEN '31-40'
WHEN T1.STAROST > 40 AND T1.STAROST<=50 THEN '41-50'
WHEN T1.STAROST > 50 THEN '>50' 
END GRUPA_STAROST
from 
(select 
PAPF.EMPLOYEE_NUMBER BROJ_RADNIKA
,PAPF.DATE_OF_BIRTH DATUM_RODJ
--,trunc((to_date(:P_DATE,'dd.mm.yyyy')-PAPF.DATE_OF_BIRTH)/365,0) STAROST
--,MONTHS_BETWEEN(to_date(:P_DATE,'dd.mm.yyyy'),PAPF.DATE_OF_BIRTH)/12 STAROST
,trunc((to_date(:P_DATE,'dd.mm.yyyy')-PAPF.DATE_OF_BIRTH)/365.25,0) STAROST
from 
per_all_people_f papf 
LEFT OUTER JOIN PER_PERSON_TYPES_TL PPT ON PAPF.PERSON_TYPE_ID=PPT.PERSON_TYPE_ID
LEFT OUTER JOIN per_all_assignments_f  PAAF on PAPF.PERSON_ID=PAAF.PERSON_ID
where 
1=1
AND PAAF.ASSIGNMENT_STATUS_TYPE_ID=1
AND (EMPLOYEE_CATEGORY IS NOT NULL OR EMPLOYMENT_CATEGORY IS NOT NULL)
AND PPT.USER_PERSON_TYPE='Radnik'
AND PPT.LANGUAGE='LSR'
AND to_date(:P_DATE,'dd.mm.yyyy') BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
AND to_date(:P_DATE,'dd.mm.yyyy') BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
) 
T1) T2
GROUP BY BR_GRUPE_STAROST, GRUPA_STAROST
ORDER BY BR_GRUPE_STAROST;