with a as
(SELECT
PAPF.EMPLOYEE_NUMBER BROJ,
PAPF.PERSON_ID,
papf.last_name||' '||papf.first_name ime
,decode(FFVV.DESCRIPTION,'Funkcija eksploatacije i održavanja','Direkcija za tehniku', 'Funkcija informacionih tehnologija','Direkcija za tehniku','Funkcija planiranja i izgradnje','Direkcija za tehniku', FFVV.DESCRIPTION) GRUPA_ZA_PLAN
FROM 
PER_ALL_PEOPLE_F PAPF  
LEFT OUTER JOIN PER_ALL_ASSIGNMENTS_F PAAF ON PAPF.PERSON_ID=PAAF.PERSON_ID
LEFT OUTER JOIN PER_PERSON_TYPES_TL PPT ON PAPF.PERSON_TYPE_ID=PPT.PERSON_TYPE_ID
LEFT OUTER JOIN fnd_flex_values_vl FFVV ON PAAF.ASS_ATTRIBUTE11=FFVV.FLEX_VALUE
WHERE
1=1
AND (EMPLOYEE_CATEGORY IS NOT NULL OR EMPLOYMENT_CATEGORY IS NOT NULL)
AND :P_DATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
AND :P_DATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
AND PPT.USER_PERSON_TYPE='Radnik'
AND PPT.LANGUAGE='LSR'
AND ffvv.FLEX_VALUE_SET_ID=(select FLEX_VALUE_SET_ID from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME like 'XXTS_GRUPA_ZA_PLAN')),
b as
(
SELECT
DISTINCT
PERSON_ID,
SPREMA,
SPREMA_RANK,
SPREMA_M_RANK
FROM
(SELECT 
Q.PERSON_ID PERSON_ID,
Q.NAME SPREMA,
QT.RANK SPREMA_RANK,
MAX(QT.RANK) OVER (PARTITION BY Q.PERSON_ID) SPREMA_M_RANK
FROM 
PER_QUALIFICATIONS_V Q LEFT OUTER JOIN PER_QUALIFICATION_TYPES QT ON Q.QUALIFICATION_TYPE_ID=QT.QUALIFICATION_TYPE_ID)
WHERE SPREMA_RANK=SPREMA_M_RANK
)
SELECT 
A.BROJ,
A.ime,
A.GRUPA_ZA_PLAN,
B.SPREMA,
B.SPREMA_RANK
FROM
A LEFT OUTER JOIN B ON A.PERSON_ID=B.PERSON_ID
where b.sprema like '%DR%'
; 


































SELECT POSITION_ID, POEI_INFORMATION1, COUNT(*) FROM HR.PER_POSITION_EXTRA_INFO 
WHERE INFORMATION_TYPE='XXTS_OBRAZOVANJE_ISKUSTVO' 
HAVING COUNT(*)>1
GROUP BY POSITION_ID, POEI_INFORMATION1
ORDER BY 1;

SELECT * FROM PER_POSITIONS;
SELECT * FROM HR.HR_ALL_POSITIONS_F WHERE POSITION_ID=74619;

SELECT * FROM PER_POSITION_EXTRA_INFO WHERE POSITION_ID=74619;


SELECT * FROM 
SELECT *  FROM PER_QUALIFICATIONS_V;
SELECT * FROM PER_QUALIFICATION_TYPES;