SELECT
T2.GRUPA_ZA_PLAN,
T2.GRUPA_STAROST,
T2.BR_GRUPE_STAROST,
count(*)
from
(SELECT
T1.GRUPA_ZA_PLAN
,CASE 
WHEN T1.STAROST < 21 THEN 1
WHEN T1.STAROST >= 21 AND T1.STAROST<31 THEN 2
WHEN T1.STAROST >= 31 AND T1.STAROST<41 THEN 3
WHEN T1.STAROST >= 41 AND T1.STAROST<51 THEN 4
WHEN T1.STAROST >= 51 AND T1.STAROST<61 THEN 5
WHEN T1.STAROST >= 61 THEN 6 
END BR_GRUPE_STAROST
,CASE 
WHEN T1.STAROST < 21 THEN '<21'
WHEN T1.STAROST >= 21 AND T1.STAROST<31 THEN '21-30'
WHEN T1.STAROST >= 31 AND T1.STAROST<41 THEN '31-40'
WHEN T1.STAROST >= 41 AND T1.STAROST<51 THEN '41-50'
WHEN T1.STAROST >= 51 AND T1.STAROST<61 THEN '51-60'
WHEN T1.STAROST >= 61 THEN '61'
END GRUPA_STAROST
FROM
(SELECT
FFVV.DESCRIPTION GRUPA_ZA_PLAN
,trunc((to_date(:P_DATE,'dd.mm.yyyy')-PAPF.DATE_OF_BIRTH)/365.242199,0) STAROST
FROM 
PER_ALL_PEOPLE_F PAPF 
LEFT OUTER JOIN PER_ALL_ASSIGNMENTS_F PAAF ON PAPF.PERSON_ID=PAAF.PERSON_ID
LEFT OUTER JOIN PER_PERSON_TYPES_TL PPT ON PAPF.PERSON_TYPE_ID=PPT.PERSON_TYPE_ID
LEFT OUTER JOIN fnd_flex_values_vl FFVV ON PAAF.ASS_ATTRIBUTE11=FFVV.FLEX_VALUE
WHERE
1=1
AND (EMPLOYEE_CATEGORY IS NOT NULL OR EMPLOYMENT_CATEGORY IS NOT NULL)
AND :P_DATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
AND :P_DATE BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
AND PPT.USER_PERSON_TYPE='Radnik'
AND PPT.LANGUAGE='LSR'
AND ffvv.FLEX_VALUE_SET_ID=(select FLEX_VALUE_SET_ID from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME like 'XXTS_GRUPA_ZA_PLAN'))T1)T2
group by 
T2.GRUPA_ZA_PLAN,
T2.BR_GRUPE_STAROST,
T2.GRUPA_STAROST
ORDER BY T2.BR_GRUPE_STAROST
; 
--GROUP BY 
--,DECODE(SUBSTR(FFVV.DESCRIPTION,0,2),'IJ','IJ',decode(FFVV.DESCRIPTION,'Funkcija eksploatacije i održavanja','Direkcija za tehniku', 'Funkcija informacionih tehnologija','Direkcija za tehniku','Funkcija planiranja i izgradnje','Direkcija za tehniku', FFVV.DESCRIPTION))
--,NVL(SUBSTR(PAAF.ASS_ATTRIBUTE5,1,(INSTR(PAAF.ASS_ATTRIBUTE5,' ',1))-1),'X');