WITH 
T0 (STAROSNE_GRUPE, NAZIV, REDOSLED)
AS (
SELECT 1 AS STAROSNE_GRANICE,
       '<21' AS NAZIV,
       1 AS REDOSLED  
FROM DUAL
UNION ALL
SELECT 2, '21-30', 2 FROM DUAL
UNION ALL
SELECT 3, '31-40', 3 FROM DUAL
UNION ALL
SELECT 4, '41-50', 4 FROM DUAL
UNION ALL
SELECT 5, '51-60', 5 FROM DUAL
UNION ALL
SELECT 6, '>=61', 6 FROM DUAL
),
T00 (QUALIFICATION_TYPE_ID, IME, KATEGORIJA, RANG)
AS (
SELECT QT.QUALIFICATION_TYPE_ID AS QUALIFICATION_TYPE_ID,
       QT.NAME AS IME,
       QT.CATEGORY AS KATEGORIJA,
       QT.RANK AS RANG
FROM HR.PER_QUALIFICATION_TYPES QT
),
T1 (LOOKUP_CODE, MEANING, REDOSLED)
AS (
SELECT LV.LOOKUP_CODE AS LOOKUP_CODE, 
       LV.MEANING AS MEANING,
       ROW_NUMBER() OVER (ORDER BY LV.LOOKUP_CODE DESC) AS REDOSLED 

FROM FND_LOOKUP_VALUES LV 
WHERE LV.LOOKUP_TYPE = 'PER_CATEGORIES'
AND LV.LOOKUP_CODE LIKE 'BA_' ||'%' 
AND LV.LANGUAGE = 'LSR'
),
T2 (PERSON_ID, NAZIV, IZBOR1, IZBOR2, REDOSLED)
AS (
SELECT Q.PERSON_ID AS PERSON_ID,
       T1.MEANING AS NAZIV,
       DENSE_RANK() OVER (PARTITION BY Q.PERSON_ID ORDER BY T00.RANG DESC) AS IZBOR1,
       ROW_NUMBER() OVER (PARTITION BY Q.PERSON_ID, T1.MEANING ORDER BY T00.RANG DESC) AS IZBOR2,
       T1.REDOSLED

FROM PER_QUALIFICATIONS_V Q, T00, T1

WHERE Q.QUALIFICATION_TYPE_ID = T00.QUALIFICATION_TYPE_ID(+)
AND T00.KATEGORIJA = T1.LOOKUP_CODE(+)
),
T3 (PERSON_ID, PERSON_TYPE_ID, DATUM_RO?ENJA, STAROST, STAROSNE_GRUPE)
AS (
SELECT P.PERSON_ID AS PERSON_ID,
       P.PERSON_TYPE_ID AS PERSON_TYPE_ID,
       NVL(P.DATE_OF_BIRTH,SYSDATE) AS DATUM_RO?ENJA,
       trunc((to_date(:P_DATUM,'dd.mm.yyyy')-P.DATE_OF_BIRTH)/365.242199,0) AS STAROST,
       (CASE WHEN trunc((to_date(:P_DATUM,'dd.mm.yyyy')-P.DATE_OF_BIRTH)/365.242199,0) <21 THEN 1
             WHEN trunc((to_date(:P_DATUM,'dd.mm.yyyy')-P.DATE_OF_BIRTH)/365.242199,0) BETWEEN 21 AND 30 THEN 2
             WHEN trunc((to_date(:P_DATUM,'dd.mm.yyyy')-P.DATE_OF_BIRTH)/365.242199,0) BETWEEN 31 AND 40 THEN 3
             WHEN trunc((to_date(:P_DATUM,'dd.mm.yyyy')-P.DATE_OF_BIRTH)/365.242199,0) BETWEEN 41 AND 50 THEN 4
             WHEN trunc((to_date(:P_DATUM,'dd.mm.yyyy')-P.DATE_OF_BIRTH)/365.242199,0) BETWEEN 51 AND 60 THEN 5
             WHEN trunc((to_date(:P_DATUM,'dd.mm.yyyy')-P.DATE_OF_BIRTH)/365.242199,0) >= 61 THEN 6 END) AS STAROSNE_GRUPE       

FROM   HR.PER_ALL_PEOPLE_F P,
       HR.PER_ALL_ASSIGNMENTS_F ASS     

WHERE  ASS.PERSON_ID = P.PERSON_ID(+)
AND (ASS.EMPLOYEE_CATEGORY IS NOT NULL OR ASS.EMPLOYMENT_CATEGORY IS NOT NULL)
AND :P_DATUM BETWEEN P.EFFECTIVE_START_DATE AND P.EFFECTIVE_END_DATE      
AND :P_DATUM BETWEEN ASS.EFFECTIVE_START_DATE AND ASS.EFFECTIVE_END_DATE
),
T4 (PERSON_TYPE_ID, USER_PERSON_TYPE)
AS (
SELECT PT.PERSON_TYPE_ID AS PERSON_TYPE_ID, 
       PT.USER_PERSON_TYPE AS USER_PERSON_TYPE

FROM HR.PER_PERSON_TYPES_TL PT
WHERE PT.LANGUAGE = 'LSR'
),
T5 (GRUPA1, GRUPA2, BROJ, REDOSLED1, REDOSLED2)
AS (
SELECT T0.NAZIV AS GRUPA1,
       T2.NAZIV AS GRUPA2,
       COUNT(*) AS BROJ,
       T0.REDOSLED AS REDOSLED1,
       T2.REDOSLED AS REDOSLED2
FROM T0, T2, T3, T4
WHERE T3.PERSON_ID = T2.PERSON_ID(+)
AND T2.IZBOR1 = 1
AND T2.IZBOR2 = 1
AND T3.PERSON_TYPE_ID = T4.PERSON_TYPE_ID(+)
AND UPPER(T4.USER_PERSON_TYPE) IN ('RADNIK', '?LAN ORGANA DRUŠTVA', 'UGOVOR O DJELU')
AND T3.STAROSNE_GRUPE = T0.STAROSNE_GRUPE(+) 
GROUP BY T0.NAZIV, T2.NAZIV, T0.REDOSLED, T2.REDOSLED

UNION ALL

SELECT TEMP0.NAZIV AS GRUPA1,
       TEMP1.MEANING AS GRUPA2,
       0 AS BROJ ,
       TEMP0.REDOSLED AS REDOSLED1,
       TEMP1.REDOSLED AS REDOSLED2
FROM
(SELECT T0.NAZIV, T0.REDOSLED FROM T0) TEMP0,
(SELECT T1.MEANING, T1.REDOSLED FROM T1) TEMP1
),
T6 (GRUPA1)
AS (
SELECT T5.GRUPA1 AS GRUPA1
FROM T5
GROUP BY T5.GRUPA1
HAVING SUM(T5.BROJ) = 0
),
T7 (GRUPA2)
AS (
SELECT T5.GRUPA2 AS GRUPA2
FROM T5
GROUP BY T5.GRUPA2
HAVING SUM(T5.BROJ) = 0
)
SELECT T5.GRUPA1,
       T5.GRUPA2,
       SUM(T5.BROJ) BROJ,
       T5.REDOSLED1,
       T5.REDOSLED2
FROM T5
WHERE T5.GRUPA1 NOT IN (SELECT T6.GRUPA1 FROM T6)
AND   T5.GRUPA2 NOT IN (SELECT T7.GRUPA2 FROM T7)
GROUP BY T5.GRUPA1, T5.GRUPA2, T5.REDOSLED1, T5.REDOSLED2
ORDER BY T5.REDOSLED1, T5.REDOSLED2