WITH T1 (LOOKUP_CODE1, MEANING1)
AS (
SELECT LV.LOOKUP_CODE AS LOOKUP_CODE1, 
       LV.MEANING AS MEANING1 
FROM FND_LOOKUP_VALUES LV 
WHERE LV.LOOKUP_TYPE = 'CONTACT'
AND   UPPER(LV.MEANING) IN ('SUPRUŽNICI BRA?NI', 'SUPRUŽNICI VANBRA?NI')
AND LV.LANGUAGE = 'LSR'
ORDER BY LV.LOOKUP_CODE
),
T2 (LOOKUP_CODE2, MEANING2)
AS (
SELECT LV.LOOKUP_CODE AS LOOKUP_CODE2, 
       LV.MEANING AS MEANING2 
FROM FND_LOOKUP_VALUES LV 
WHERE LV.LOOKUP_TYPE = 'CONTACT'
AND   UPPER(LV.MEANING) IN ('DJECA BRA?NA', 'DJECA VANBRA?NA', 'DJECA USVOJENA', 'PASTORCI')
AND LV.LANGUAGE = 'LSR'
ORDER BY LV.LOOKUP_CODE
),
T3 (LOOKUP_CODE3, MEANING3)
AS (
SELECT LV.LOOKUP_CODE AS LOOKUP_CODE3, 
       LV.MEANING AS MEANING3 
FROM FND_LOOKUP_VALUES LV 
WHERE LV.LOOKUP_TYPE = 'CONTACT'
AND   UPPER(LV.MEANING) IN ('OTAC', 'MAJKA')
AND LV.LANGUAGE = 'LSR'
ORDER BY LV.LOOKUP_CODE
),
T4 (LOOKUP_CODE4, MEANING4)
AS (
SELECT LV.LOOKUP_CODE AS LOOKUP_CODE4, 
       LV.MEANING AS MEANING4 
FROM FND_LOOKUP_VALUES LV 
WHERE LV.LOOKUP_TYPE = 'CONTACT'
AND LV.LANGUAGE = 'LSR'
ORDER BY LV.MEANING
),
T5 (PERSON_TYPE_ID, USER_PERSON_TYPE)
AS (
SELECT PT.PERSON_TYPE_ID AS PERSON_TYPE_ID, 
       PT.USER_PERSON_TYPE AS USER_PERSON_TYPE
FROM HR.PER_PERSON_TYPES_TL PT
WHERE PT.LANGUAGE = 'LSR' 
AND UPPER(PT.USER_PERSON_TYPE) IN ('RADNIK', '?LAN ORGANA DRUŠTVA', 'UGOVOR O DJELU')
),
T6 (PERSON_TYPE_ID, USER_PERSON_TYPE)
AS (
SELECT PT.PERSON_TYPE_ID AS PERSON_TYPE_ID, 
       PT.USER_PERSON_TYPE AS USER_PERSON_TYPE
FROM HR.PER_PERSON_TYPES_TL PT
WHERE PT.LANGUAGE = 'LSR'
),
T7 (IDENTIFIKATOR1, VREDNOST1)
AS (
SELECT VL.FLEX_VALUE_MEANING AS IDENTIFIKATOR1, VL.DESCRIPTION AS VREDNOST1
FROM   FND_FLEX_VALUE_SETS VS, FND_FLEX_VALUES_VL VL, FND_FLEX_VALUES_TL TL
WHERE  VL.FLEX_VALUE_SET_ID = VS.FLEX_VALUE_SET_ID
AND    VL.FLEX_VALUE_ID = TL.FLEX_VALUE_ID
AND    VS.FLEX_VALUE_SET_NAME = 'XXTS_GRUPA_ZA_PLAN'
AND    TL.LANGUAGE = 'LSR'
),
T8 (IDENTIFIKATOR2, VREDNOST2) 
AS (
SELECT VL.FLEX_VALUE_MEANING AS IDENTIFIKATOR2, VL.DESCRIPTION AS VREDNOST2
FROM   FND_FLEX_VALUE_SETS VS, FND_FLEX_VALUES_VL VL, FND_FLEX_VALUES_TL TL
WHERE  VL.FLEX_VALUE_SET_ID = VS.FLEX_VALUE_SET_ID
AND    VL.FLEX_VALUE_ID = TL.FLEX_VALUE_ID
AND    VS.FLEX_VALUE_SET_NAME = 'XXTS_POSTANSKI_BROJEVI_BA'
AND    TL.LANGUAGE = 'LSR'
),
T9 (PERSON_IME, PERSON_PREZIME, PERSON_ID, PERSON1_TYPE_ID, KONTAKT_IME, KONTAKT_PREZIME, DATUM_RO?ENJA, STAROST, KONTAKT_ID, PERSON2_TYPE_ID, CONTACT_TYPE)
AS (
SELECT P1.FIRST_NAME AS PERSON_IME,
       P1.LAST_NAME AS PERSON_PREZIME,     
       CR.PERSON_ID AS PERSON_ID,
       P1.PERSON_TYPE_ID AS PERSON1_TYPE_ID,
       P2.FIRST_NAME AS KONTAKT_IME,
       P2.LAST_NAME AS KONTAKT_PREZIME,
       NVL(P2.DATE_OF_BIRTH,TO_DATE(SYSDATE,'DD.MM.RRRR')) AS DATUM_RO?ENJA,
       EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM NVL(P2.DATE_OF_BIRTH,SYSDATE)) AS STAROST,
       CR.CONTACT_PERSON_ID AS KONTAKT_ID,
       P2.PERSON_TYPE_ID AS PERSON2_TYPE_ID,
       LV.MEANING AS CONTACT_TYPE 
FROM PER_CONTACT_RELATIONSHIPS CR, 
     HR.PER_ALL_PEOPLE_F P1, HR.PER_ALL_PEOPLE_F P2, 
     FND_LOOKUP_VALUES LV 
WHERE CR.PERSON_ID = P1.PERSON_ID(+)
AND CR.CONTACT_PERSON_ID = P2.PERSON_ID(+)
AND CR.CONTACT_TYPE = LV.LOOKUP_CODE(+)
AND LV.LOOKUP_TYPE = 'CONTACT'
AND LV.LANGUAGE = 'LSR'
AND SYSDATE BETWEEN P1.EFFECTIVE_START_DATE AND P1.EFFECTIVE_END_DATE
AND SYSDATE BETWEEN P2.EFFECTIVE_START_DATE AND P2.EFFECTIVE_END_DATE
ORDER BY P2.DATE_OF_BIRTH   
),
T10 (PERSON_ID, LOCATION_ID, ORGANIZATION_ID, ASS_ATTRIBUTE11, POSTAL_CODE)
AS (
SELECT ASS.PERSON_ID AS PERSON_ID,
       ASS.LOCATION_ID AS LOCATION_ID,
       ASS.ORGANIZATION_ID AS ORGANIZATION_ID,
       NVL(ASS.ASS_ATTRIBUTE11,'00') AS ASS_ATTRIBUTE11,
       LOC.POSTAL_CODE AS POSTAL_CODE       
FROM   HR.PER_ALL_ASSIGNMENTS_F ASS,
       HR_LOCATIONS LOC,
       HR_ALL_ORGANIZATION_UNITS ORG     
WHERE  ASS.LOCATION_ID = LOC.LOCATION_ID(+)
AND    ASS.ORGANIZATION_ID = ORG.ORGANIZATION_ID(+)
AND SYSDATE BETWEEN ASS.EFFECTIVE_START_DATE AND ASS.EFFECTIVE_END_DATE
)
SELECT UPPER(NVL(T7.VREDNOST1,'NEPOZNATA_GRUPA')) GRUPA,
       UPPER(NVL(T8.VREDNOST2,'NEPOZNATA_LOKACIJA')) LOKACIJA,
       T9.PERSON_PREZIME PREZIME,
       T9.PERSON_IME IME,
       T9.KONTAKT_IME IME_DETETA,
       TO_CHAR(NVL(T9.DATUM_RO?ENJA,TO_DATE(SYSDATE,'DD.MM.RRRR')),'DD.MM.RRRR') DATUM_RO?ENJA,
       T9.STAROST
FROM T9, T10, T6 TP61, T6 TP62, T8, T7     
WHERE T9.PERSON_ID = T10.PERSON_ID(+)
AND T10.POSTAL_CODE = T8.IDENTIFIKATOR2(+)
AND T10.ASS_ATTRIBUTE11 = T7.IDENTIFIKATOR1(+)
AND T7.VREDNOST1 IN (SELECT VL.DESCRIPTION
FROM   FND_FLEX_VALUE_SETS VS, FND_FLEX_VALUES_VL VL, FND_FLEX_VALUES_TL TL
WHERE  VL.FLEX_VALUE_SET_ID = VS.FLEX_VALUE_SET_ID
AND    VL.FLEX_VALUE_ID = TL.FLEX_VALUE_ID
AND    VS.FLEX_VALUE_SET_NAME = 'XXTS_GRUPA_ZA_PLAN'
AND    TL.LANGUAGE = 'LSR'
ORDER BY 1)
AND UPPER(T9.CONTACT_TYPE) IN ('DJECA BRA?NA', 'DJECA VANBRA?NA', 'DJECA USVOJENA', 'PASTORCI')
AND T9.PERSON1_TYPE_ID = TP61.PERSON_TYPE_ID(+)
AND T9.PERSON2_TYPE_ID = TP62.PERSON_TYPE_ID(+)
AND UPPER(TP61.USER_PERSON_TYPE) IN ('RADNIK')
AND UPPER(TP62.USER_PERSON_TYPE) IN ('KONTAKT OSOBA')
AND T9.STAROST < 10
ORDER BY T9.STAROST;