SELECT * FROM XXCO_HR_ASS_MJESTA_TROSKA@TRANSCON WHERE EMPLOYEE_NUMBER IN (430,20762, 7912,3759,93,65,53);

SELECT * FROM HR.PER_ALL_ASSIGNMENTS_F WHERE ASSIGNMENT_NUMBER='3128';

SELECT * FROM HR.HR_ALL_ORGANIZATION_UNITS WHERE ORGANIZATION_ID=2628;

SELECT * FROM XXCO_HR_ASSIGNMENTS@TRANSCON WHERE EMPLOYEE_NUMBER='3128';

SELECT * FROM XXCO_HR_ORGANIZATION@TRANSCON WHERE ORG_ID_EBS=2628;

SELECT * FROM XXCO_HR_ORGANIZATION@TRANSCON WHERE ID_ORGANizaCIJE_ORIG_SEMA=5000;

6238

select 
ID_ORGANIZACIJE_ORIG ORG_ID
,lpad(' ',2*level,' ')||substr(ORGANIZATION_NAME,instr(ORGANIZATION_NAME,'.')+1) ORG_NAME
,ID_ORGANIZACIJE_ORIG_SEMA OS_ID
,LEVEL
from XXCO_HR_ORGANIZATION@TRANSCON
start with ID_ORGANIZACIJE_ORIG_SEMA=5000
--WHERE LEVEL=6
CONNECT by prior ID_ORGANIZACIJE_ORIG_SEMA=NAD_ORIG_SEMA
;