SELECT
description,
FLEX_VALUE_MEANING
from 
APPLSYS.FND_FLEX_VALUES_tl 
where 
1=1
and FLEX_VALUE_ID in (select flex_value_id from FND_FLEX_VALUES where FLEX_VALUE_SET_ID=(select FLEX_VALUE_SET_ID from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME like '%XXTS_STRUCNA_SPREMA%'))
and language='LSR'
ORDER BY DESCRIPTION;

SELECT * FROM PER_JOBS;
SELECT * FROM PER_POSITIONS;


SELECT * FROM PER_PERSON_TYPES_TL;

SELECT * FROM PER_ALL_PEOPLE_F WHERE PERSON_ID=19439;

SELECT HR_PERSON_TYPE_USAGE_INFO.GET_USER_PERSON_TYPE(TO_DATE('31-12-2015','DD-MM-YYYY'),19439) FROM DUAL;


SELECT * FROM per_person_type_usages_f WHERE PERSON_ID=19439;

select * from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME like '%STRU%';
