SELECT
PAPF.PERSON_ID PERSON_ID,
PAPF.EMPLOYEE_NUMBER EMPLOYEE_NUMBER,
PAPF.LAST_NAME||' '||PAPF.FIRST_NAME IME
FROM
PER_ALL_PEOPLE_F PAPF
LEFT OUTER JOIN PER_ALL_ASSIGNMENTS_F PAAF ON PAPF.PERSON_ID=PAAF.PERSON_ID
LEFT OUTER JOIN PER_PERSON_TYPES_TL PPTL ON PAPF.PERSON_TYPE_ID=PPTL.PERSON_TYPE_ID
WHERE
1=1
AND PAAF.ASSIGNMENT_STATUS_TYPE_ID=1
AND (PAAF.EMPLOYEE_CATEGORY IS NOT NULL OR PAAF.EMPLOYMENT_CATEGORY IS NOT NULL)
AND :P_DATUM BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
AND :P_DATUM BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
AND PPTL.LANGUAGE = 'LSR'
AND UPPER(PPTL.USER_PERSON_TYPE)=UPPER('Radnik')
ORDER BY 1;