SELECT 
 T.OPSTINA
,T.STRUKA
,T.RANG
,COUNT(*) BROJ
FROM
(SELECT 
 QT.NAME                        STRUKA
,QT.RANK                        RANG
,P.EMPLOYEE_NUMBER
,EI.PEI_INFORMATION1            OPSTINA
,MAX(QT.RANK) OVER (PARTITION BY P.EMPLOYEE_NUMBER)  NAJVISI_STEPEN
FROM 
 HR.PER_ALL_PEOPLE_F    P
,PER_QUALIFICATIONS_V   Q
,HR.PER_QUALIFICATION_TYPES QT
,PER_ALL_ASSIGNMENTS_F  ASS
,HR.PER_PEOPLE_EXTRA_INFO EI
,PER_PERSON_TYPES_TL      PT
WHERE 
    P.PERSON_ID = ASS.PERSON_ID
AND Q.PERSON_ID = P.PERSON_ID
AND QT.QUALIFICATION_TYPE_ID = Q.QUALIFICATION_TYPE_ID
AND :P_DATE BETWEEN ASS.EFFECTIVE_START_DATE AND ASS.EFFECTIVE_END_DATE
AND :P_DATE BETWEEN P.EFFECTIVE_START_DATE AND P.EFFECTIVE_END_DATE
AND ASS.ASSIGNMENT_STATUS_TYPE_ID=1
AND (ASS.EMPLOYEE_CATEGORY IS NOT NULL OR ASS.EMPLOYMENT_CATEGORY IS NOT NULL)
AND EI.PERSON_ID = P.PERSON_ID
AND EI.INFORMATION_TYPE = 'XXTS_OPSTINA_DOPRINOSA'
AND P.PERSON_TYPE_ID = PT.PERSON_TYPE_ID
AND PT.LANGUAGE = 'LSR'
AND UPPER(PT.USER_PERSON_TYPE) = UPPER('Radnik')
) T
WHERE T.RANG = T.NAJVISI_STEPEN
GROUP BY
 T.OPSTINA
,T.STRUKA
,T.RANG
ORDER BY 1, 3 DESC;


SELECT * FROM PER_QUALIFICATION_TYPES;
SELECT * FROM PER_PEOPLE_EXTRA_INFO WHERE INFORMATION_TYPE='XXTS_OPSTINA_DOPRINOSA';

SELECT
PERSON_ID,
SPREMA,
SPREMA_RANK,
SPREMA_M_RANK
FROM
(SELECT 
Q.PERSON_ID PERSON_ID,
Q.NAME SPREMA,
QT.RANK SPREMA_RANK,
MAX(QT.RANK) OVER (PARTITION BY Q.PERSON_ID) SPREMA_M_RANK
FROM 
PER_QUALIFICATIONS_V Q LEFT OUTER JOIN PER_QUALIFICATION_TYPES QT ON Q.QUALIFICATION_TYPE_ID=QT.QUALIFICATION_TYPE_ID)
WHERE SPREMA_RANK=SPREMA_M_RANK;



SELECT POSITION_ID, POEI_INFORMATION1, COUNT(*) FROM HR.PER_POSITION_EXTRA_INFO 
WHERE INFORMATION_TYPE='XXTS_OBRAZOVANJE_ISKUSTVO' 
HAVING COUNT(*)>1
GROUP BY POSITION_ID, POEI_INFORMATION1
ORDER BY 1;

SELECT * FROM PER_POSITIONS;
SELECT * FROM HR.HR_ALL_POSITIONS_F WHERE POSITION_ID=74619;

SELECT * FROM PER_POSITION_EXTRA_INFO WHERE POSITION_ID=74619;


SELECT * FROM 
SELECT *  FROM PER_QUALIFICATIONS_V;
SELECT * FROM PER_QUALIFICATION_TYPES;

select flex_value_set_id from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME='XXTS_STRUCNA_SPREMA';

select 
description potrebna_ss
,flex_value_meaning sifra_ss
from FND_FLEX_VALUES_TL 
where FLEX_VALUE_ID in 
(select FLEX_VALUE_ID from FND_FLEX_VALUES 
where flex_value_set_id=(select flex_value_set_id from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME='XXTS_STRUCNA_SPREMA')) and LANGUAGE='LSR';

SELECT POSITION_ID, POEI_INFORMATION1 FROM HR.PER_POSITION_EXTRA_INFO 
WHERE INFORMATION_TYPE='XXTS_OBRAZOVANJE_ISKUSTVO';
--minus


select
ppei.POSITION_ID
,ppei.POEI_INFORMATION1
,ffvt.description potrebna_ss
,ffvt.flex_value_meaning sifra_ss
from PER_POSITION_EXTRA_INFO ppei left outer join FND_FLEX_VALUES_TL ffvt on ppei.POEI_INFORMATION1=ffvt.flex_value_meaning
where FLEX_VALUE_ID in 
(select FLEX_VALUE_ID from FND_FLEX_VALUES 
where flex_value_set_id=(select flex_value_set_id from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME='XXTS_STRUCNA_SPREMA')) and LANGUAGE='LSR';









