SELECT * FROM PER_POSITIONS_V;
SELECT * FROM PER_JOBS;

select *  from PER_POSITION_EXTRA_INFO where INFORMATION_TYPE='XXTS_OBRAZOVANJE_ISKUSTVO';
select *  from PER_QUALIFICATION_TYPES;

SELECT * FROM FND_FLEX_VALUES_VL WHERE FLEX_VALUE_SET_ID=1015814;

SELECT * FROM  FND_FLEX_VALUE_SETS FFVS WHERE FFVS.FLEX_VALUE_SET_NAME='XXTS_STRUCNA_SPREMA';