select * from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME like '%XXTS%';
SELECT * FROM APPLSYS.FND_FLEX_VALIDATION_TABLES WHERE FLEX_VALUE_SET_ID IN (select FLEX_VALUE_SET_ID from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME like '%XXTS%' AND VALIDATION_TYPE='F');
SELECT * FROM FND_FLEX_VALUES;


SELECT
FFVT.FLEX_VALUE_MEANING VRIJEDNSOT,
FFVT.DESCRIPTION OPIS,
FFVS.FLEX_VALUE_SET_NAME
from 
APPLSYS.FND_FLEX_VALUES_tl FFVT
LEFT OUTER JOIN FND_FLEX_VALUES FFV ON FFVT.FLEX_VALUE_ID=FFV.FLEX_VALUE_ID
LEFT OUTER JOIN APPLSYS.FND_FLEX_VALUE_SETS FFVS ON FFV.FLEX_VALUE_SET_ID=FFVS.FLEX_VALUE_SET_ID
where 
1=1
AND FFVS.FLEX_VALUE_SET_NAME LIKE '%XXTS_POVREDA_R_OBAVEZE%'
--and FLEX_VALUE_ID in (select flex_value_id from FND_FLEX_VALUES where FLEX_VALUE_SET_ID IN (select FLEX_VALUE_SET_ID from FND_FLEX_VALUE_SETS where FLEX_VALUE_SET_NAME like '%XXTS%'))
and language='LSR'
ORDER BY 3;